gpu: 0



model:
  input_height : 112
  input_width : 112
  encoder_model: "resnet18"
  embedding_size: 512
  num_projection_layers: 1
  projection_size: 256
  projection_hidden_layer_size: 4096
  name: "byol_model"
  ema_tau : 0.99



train:
  learning_rate: 0.003
  batch_size: 256
  num_epochs: 100
  print_every: 50
  checkpoint_every: 20
  use_percent_train_data : 1.0

  augmentation:
    view_1:
      resize_crop:
        apply_probability : 1.0
      random_flip:
        apply_probability : 0.5
      colour_jitter:
        apply_probability: 0.8
        brightness_delta : 0.4
        contrast_delta : 0.4
        saturation_delta: 0.2
        hue_delta: 0.1
      colour_drop:
        apply_probability : 0.2
      gaussian_blur:
        apply_probability: 1.0
        kernel_size: [11, 11]
        sigma: [0.1, 2.0]
      solarize:
        apply_probability : 0.0
        threshold: 0.5
      normalise:
        mean : 0.5
        std : 0.25
    view_2:
      resize_crop:
        apply_probability : 1.0
      random_flip:
        apply_probability : 0.5
      colour_jitter:
        apply_probability: 0.8
        brightness_delta: 0.4
        contrast_delta: 0.4
        saturation_delta: 0.2
        hue_delta: 0.1
      colour_drop:
        apply_probability : 0.2
      gaussian_blur:
        apply_probability: 0.1
        kernel_size: [11, 11]
        sigma: [ 0.1, 2.0 ]
      solarize:
        apply_probability: 0.2
        threshold: 0.5
      normalise:
        mean: 0.5
        std: 0.25

fine_tune:
  learning_rate: 0.005
  momentum : 0.9
  batch_size: 256
  num_epochs: 30
  print_every: 50
  checkpoint_every: 15
  use_percent_train_data : 1.0
  use_percent_train_data_as_val : 0.1
  num_classes : 10
  validate_every : 1
  freeze_encoder : False

  augmentation:
    resize_crop:
      apply_probability: 1.0
    random_flip:
      apply_probability: 0.5
    normalise:
      mean: 0.5
      std: 0.25
test:
  augmentation:
    normalise:
      mean: 0.5
      std: 0.25


