batch_size: 256
num_epochs: 80
checkpoint_every: 15
percent_data_to_use : 1.0
percent_train_to_use_as_val : 0.1
num_classes : 10
validate_every : 1
freeze_encoder : True

optimiser_params:
  lr : 0.003

augmentation:
  resize_crop:
    apply_probability: 0.0
  random_flip:
    apply_probability: 0.0
  normalise:
    mean: 0.5
    std: 0.25


