batch_size: 256
num_epochs: 100
checkpoint_every: 50
use_percent_train_data : 1.0

optimiser_params:
  lr : 0.005
  weight_decay : 0.0000015


augmentation:
  view_1:
    resize_crop:
      apply_probability : 1.0
    random_flip:
      apply_probability : 0.5
    colour_jitter:
      apply_probability: 0.8
      brightness_delta : 0.4
      contrast_delta : 0.4
      saturation_delta: 0.2
      hue_delta: 0.1
    colour_drop:
      apply_probability : 0.2
    gaussian_blur:
      apply_probability: 1.0
      kernel_size: [3, 3]
      sigma: [0.1, 2.0]
    solarize:
      apply_probability : 0.0
      threshold: 0.5
    normalise:
      mean : 0.5
      std : 0.25
  view_2:
    resize_crop:
      apply_probability : 1.0
    random_flip:
      apply_probability : 0.5
    colour_jitter:
      apply_probability: 0.8
      brightness_delta: 0.4
      contrast_delta: 0.4
      saturation_delta: 0.2
      hue_delta: 0.1
    colour_drop:
      apply_probability : 0.2
    gaussian_blur:
      apply_probability: 0.1
      kernel_size: [3, 3]
      sigma: [ 0.1, 2.0 ]
    solarize:
      apply_probability: 0.2
      threshold: 0.5
    normalise:
      mean: 0.5
      std: 0.25


